### ISSUE TITLE
css is not working

### ISSUE THREAD

**Issue by deepakydv9315** [AlekseiMakonovitskii/Landing-Page-1#1]
css is not working

![image](https://user-images.githubusercontent.com/76609302/178159492-f89bf89c-a9bb-4494-84f6-69dff20179d6.png)

**Comment by AlekseiMakonovitskii** [comment]
thanks for your help in solving this problem

**Comment by deepakydv9315** [comment]
yeah :) let's follow each other and help each other in our dev journey
